# Generated by Django 5.1.6 on 2025-02-22 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checker", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="website",
            name="last_checked",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="website",
            name="status",
            field=models.CharField(
                choices=[("UP", "Up"), ("DOWN", "Down"), ("NONE", "None")],
                default="NONE",
                max_length=4,
            ),
        ),
    ]
