# Generated by Django 5.1.6 on 2025-02-22 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checker", "0002_website_last_checked_website_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="website",
            name="status",
            field=models.CharField(
                choices=[("UP", "Up"), ("DOWN", "Down")], default="NONE", max_length=4
            ),
        ),
        migrations.AlterField(
            model_name="websitestatusevent",
            name="new_status",
            field=models.CharField(
                choices=[("UP", "Up"), ("DOWN", "Down")], max_length=4
            ),
        ),
        migrations.AlterField(
            model_name="websitestatusevent",
            name="old_status",
            field=models.CharField(
                choices=[("UP", "Up"), ("DOWN", "Down")], max_length=4
            ),
        ),
    ]
