# Generated by Django 5.1.6 on 2025-02-22 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checker", "0003_alter_website_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="website",
            name="last_checked",
            field=models.DateTimeField(),
        ),
    ]
