# Generated by Django 5.1.6 on 2025-02-22 17:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checker", "0004_alter_website_last_checked"),
    ]

    operations = [
        migrations.AddField(
            model_name="website",
            name="last_status_change",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 2, 22, 17, 2, 31, 469261, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
    ]
